# Generated by Django 2.0.4 on 2018-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0004_auto_20180427_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='career',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_a_programmer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='went_to_what_school',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
